en:
  languageCode: en-us
  contentDir: content/en

it:
  languageCode: it
  contentDir: content/it
  title: sbrzt
  params:
    description: Il sito personale di Sebastian Barzaghi, ricercatore in Digital Humanities specializzato in Linked Open Data e Open Science.
  menu:
    main:
      - name: Biografia
        url: '#about'
        weight: 10
      - name: Post
        url: '#posts'
        weight: 40
      - name: Progetti
        url: '#projects'
        weight: 30
      - name: Pubblicazioni
        url: '#featured'
        weight: 20
      - name: Contatti
        url: '#contact'
        weight: 50
  
