main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Posts
    url: '#posts'
    weight: 40
  - name: Projects
    url: '#projects'
    weight: 30
  - name: Publications
    url: '#featured'
    weight: 20
  - name: Contact
    url: '#contact'
    weight: 50
